# Generated by Django 5.2.15 on 2026-07-13 21:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjecaoUsuario",
            fields=[
                (
                    "usuario_id",
                    models.UUIDField(primary_key=True, serialize=False),
                ),
                (
                    "login",
                    models.CharField(
                        db_index=True, max_length=20, unique=True
                    ),
                ),
                (
                    "rf",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "cpf",
                    models.CharField(
                        blank=True, db_index=True, max_length=11, null=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("situacao", models.CharField(max_length=20)),
                (
                    "dre_codigo",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("contrato_externo", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Projeção de usuário",
                "verbose_name_plural": "Projeções de usuários",
            },
        ),
        migrations.CreateModel(
            name="PermissaoUsuario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("codigo", models.IntegerField()),
                (
                    "descricao",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissoes",
                        to="perfil.projecaousuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permissão de usuário",
                "verbose_name_plural": "Permissões de usuários",
            },
        ),
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfis",
                        to="perfil.projecaousuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de usuário",
                "verbose_name_plural": "Perfis de usuários",
            },
        ),
    ]
