# Generated by Django 5.2.16 on 2026-07-19 23:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModuloPermissaoUsuario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sistema_id", models.IntegerField()),
                ("sistema_nome", models.CharField(max_length=255)),
                ("modulo_id", models.IntegerField()),
                ("modulo_nome", models.CharField(max_length=255)),
                ("consultar", models.BooleanField(default=False)),
                ("inserir", models.BooleanField(default=False)),
                ("alterar", models.BooleanField(default=False)),
                ("excluir", models.BooleanField(default=False)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modulos_permissao",
                        to="perfil.projecaousuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permissão de módulo do usuário",
                "verbose_name_plural": "Permissões de módulos do usuário",
            },
        ),
        migrations.DeleteModel(
            name="PermissaoUsuario",
        ),
        migrations.AddConstraint(
            model_name="modulopermissaousuario",
            constraint=models.UniqueConstraint(
                fields=("usuario", "sistema_id", "modulo_id"),
                name="uniq_modulo_permissao_usuario",
            ),
        ),
    ]
