# Generated by Django 5.2.15 on 2026-09-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "perfil",
            "0002_modulopermissaousuario_delete_permissaousuario_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilusuario",
            name="sistema_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
