[pytest]
DJANGO_SETTINGS_MODULE = token_ms.settings_test
python_files = tests/test_*.py tests/**/test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    --reuse-db
    -v
    --cov=core
    --cov=enrichment
    --cov=exchange
    --cov-report=term-missing
    --cov-fail-under=90
