# Generated by Django 5.2.16 on 2026-07-17 19:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("perfil", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AtributoComplementarUsuario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rf",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True, db_index=True, max_length=11, null=True
                    ),
                ),
                (
                    "matricula",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                (
                    "nome",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "tipo_usuario",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "cargo",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "funcao",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "unidade",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "unidade_codigo",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "dre",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("ue", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "cod_escola",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "turma",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "tipo_acesso",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "situacao",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "fonte",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "id_execucao",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="atributos_complementares",
                        to="perfil.projecaousuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atributo complementar de usuário",
                "verbose_name_plural": "Atributos complementares de usuários",
            },
        ),
    ]
