# Generated by Django 5.2.17 on 2026-08-26 16:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atributos_complementares", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VinculoAtributoComplementar",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tipo_vinculo", models.CharField(max_length=20)),
                (
                    "codigo_vinculo_origem",
                    models.CharField(
                        help_text="Chave natural do vínculo na origem (SE1426), usada para upsert idempotente.",
                        max_length=50,
                    ),
                ),
                (
                    "cargo_codigo",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "cargo_nome",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "unidade_codigo",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "unidade_nome",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dre_codigo",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "situacao",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "data_inicio",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("vigente", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "atributo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculos",
                        to="atributos_complementares.atributocomplementarusuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vínculo de atributo complementar",
                "verbose_name_plural": "Vínculos de atributos complementares",
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "atributo",
                            "tipo_vinculo",
                            "codigo_vinculo_origem",
                        ),
                        name="vinculo_unico_por_atributo_tipo_origem",
                    )
                ],
            },
        ),
    ]
