# Generated by Django 5.1.15 on 2026-05-13 13:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ETLBatchLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('execution_id', models.UUIDField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('users_received', models.IntegerField(default=0)),
                ('users_created', models.IntegerField(default=0)),
                ('users_updated', models.IntegerField(default=0)),
                ('users_failed', models.IntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='UserClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login', models.CharField(db_index=True, max_length=64, unique=True)),
                ('cpf', models.CharField(blank=True, db_index=True, max_length=14)),
                ('rf', models.CharField(blank=True, db_index=True, max_length=20)),
                ('matricula', models.CharField(blank=True, db_index=True, max_length=20)),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('source', models.CharField(blank=True, max_length=32)),
                ('tipo_usuario', models.CharField(blank=True, max_length=32)),
                ('claims', models.JSONField(blank=True, default=dict)),
                ('execution_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['login'],
            },
        ),
    ]
